# Generated by Django 5.2.3 on 2025-12-17 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_communitymember_communities_joined__6de397_idx'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post', '-created_at'], name='posts_like_post_id_476f02_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_post_created_183a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', '-created_at'], name='posts_post_communi_ddf459_idx'),
        ),
    ]
