# Generated by Django 5.2.3 on 2025-12-17 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='communitymember',
            index=models.Index(fields=['-joined_at'], name='communities_joined__6de397_idx'),
        ),
    ]
